import { Crown, Flame, Sparkles } from "lucide-react";

export interface Product {
  id: number;
  name: string;
  price: number;
  category: string;
  image: string;
  description: string;
}

export interface Category {
  key: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  image: string;
  gradient: string;
  badge: string;
  products: Product[];
}

export const allProducts: Product[] = [
  {
    id: 61,
    name: "مواسير",
    price: 40,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "مواسير بلدي طازجة، مقرمشة ولذيذة، مثالية للشوي أو القلي",
  },
  {
    id: 62,
    name: "بوش عجالي",
    price: 119.99,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "بوش عجالي طازج بجودة عالية، مناسب لجميع أطباق العجال",
  },
  {
    id: 63,
    name: "الطحال",
    price: 140,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "طحال بلدي طازج، غني بالحديد والمعادن، طعم مميز ومحبب",
  },
  {
    id: 64,
    name: "حلويات",
    price: 120.99,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description:
      "حلويات لحم بلدي طازجة، مقلية ومقرمشة، من أشهى الأكلات الشعبية",
  },
  {
    id: 65,
    name: "دهن كلاوي",
    price: 109.99,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "دهن كلاوي بلدي نقي، يضيف نكهة غنية للأطباق المختلفة",
  },
  {
    id: 66,
    name: "فشة",
    price: 90,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "فشة بلدي طازجة نظيفة ومحضرة بعناية لتقديم أفضل جودة",
  },
  {
    id: 79,
    name: "مخاصي",
    price: 349.99,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "مخاصي بلدي طازج، حاجة فاخرة للمحبين، جودة ممتازة",
  },
  {
    id: 80,
    name: "كبده+قلب وكلاوي",
    price: 459.99,
    category: "حجز مسبق",
    image: "/products/كبدة.png",
    description:
      "تشكيلة كبدة وقلب وكلاوي بلدي طازجة، باقة متنوعة من أطيب المقبلات",
  },
  {
    id: 81,
    name: "مخ",
    price: 219.99,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "مخ بلدي طازج ونظيف، يقدم بالطريقة التقليدية الشهية",
  },
  {
    id: 82,
    name: "لحمه راس",
    price: 339.99,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "لحمة راس بلدي طازجة، مثالية لإعداد أشهى الوجبات التقليدية",
  },
  {
    id: 83,
    name: "كوارع",
    price: 339.99,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "كوارع بلدي نظيفة ومحضرة بعناية، طازجة ولذيذة",
  },
  {
    id: 84,
    name: "عكاوي",
    price: 334.99,
    category: "حجز مسبق",
    image: "/products/dummy.png",
    description: "عكاوي بلدي طازجة، مقرمشة ومقلية بعناية على النار",
  },
  {
    id: 85,
    name: "قلب وكلاوي",
    price: 344.99,
    category: "حجز مسبق",
    image: "/products/كلاوي.png",
    description: "قلب وكلاوي بلدي طازجين، من أجود المقبلات البلدي",
  },
  {
    id: 86,
    name: "كبده - بلدي صافي",
    price: 499.99,
    category: "حجز مسبق",
    image: "/products/كبدة.png",
    description: "كبده بلدي صافي طازجة، أعلى جودة ونضارة، طعم لا يُنسى",
  },

  {
    id: 67,
    name: "لحم حواوشي بلدي",
    price: 359.99,
    category: "جاهز للتسوية",
    image: "/products/رغيف-حواوشى-بلدي.png",
    description: "لحم حواوشي بلدي محشو بالتوابل والبصل، جاهز للتسوية مباشرة",
  },
  {
    id: 68,
    name: "سجق شرقي",
    price: 399.99,
    category: "جاهز للتسوية",
    image: "/products/سجق.jpg",
    description: "سجق شرقي بلدي بالتوابل الأصلية، مثالي للشوي أو القلي",
  },
  {
    id: 69,
    name: "برجر بلدي",
    price: 409.99,
    category: "جاهز للتسوية",
    image: "/products/برجر-بلدي.png",
    description: "برجر بلدي 100% لحم بقري، طازج ومحضر يدوياً بالتوابل",
  },
  {
    id: 70,
    name: "كفتة بلدي",
    price: 409.99,
    category: "جاهز للتسوية",
    image: "/products/كفتة-بلدي.png",
    description: "كفتة بلدي بالبقدونس والتوابل، مثالية للشوي والقلي",
  },
  {
    id: 71,
    name: "كفتة ارز",
    price: 279.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "كفتة ارز بلدي تقليدية بالأرز والتوابل، جاهزة للطبخ",
  },
  {
    id: 72,
    name: "شاورما لحمة متبلة",
    price: 434.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "شاورما لحمة متبلة بالتوابل الشرقية، جاهزة للشواء",
  },
  {
    id: 73,
    name: "برجر شيدر",
    price: 419.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "برجر شيدر بلدي فاخر بالجبن، وجبة شهية لا تقاوم",
  },
  {
    id: 74,
    name: "برجر رومي",
    price: 419.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "برجر رومي خفيف ولذيذ، محضر من أجود اللحوم",
  },
  {
    id: 75,
    name: "شاورما لحم 15%",
    price: 479.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "شاورما لحن 15% دهون، صحي ولذيذ، متبل بالتواصل الأصلية",
  },
  {
    id: 76,
    name: "مفروم بلدي عادي 30%",
    price: 424.99,
    category: "جاهز للتسوية",
    image: "/products/مفروم-بلدي.png",
    description: "مفروم بلدي عادي 30% دهون، مثالي للكفتة والمعكرونة",
  },
  {
    id: 77,
    name: "ممبار",
    price: 169.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "ممبار بلدي نظيف ومحضر، مقرمشه ولذيذ جداً",
  },
  {
    id: 78,
    name: "ممبار محشي",
    price: 139.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "ممبار محشي بالأرز والتوابل، جاهز للطبخ مباشرة",
  },
  {
    id: 91,
    name: "كباب حلة",
    price: 459.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "كباب حلة بلدي بالتوابل، جاهز للطبخ بسهولة",
  },
  {
    id: 92,
    name: "كولاتة",
    price: 479.99,
    category: "جاهز للتسوية",
    image: "/products/dummy.png",
    description: "كولاتة بلدي لذيذة ومتبلة بالتوابل الشرقية الأصلية",
  },

  {
    id: 87,
    name: "عمود سن عادي 30%",
    price: 444.99,
    category: "الكندوز",
    image: "/products/لحم-عمود-سن-قليل-الدسم.png",
    description: "عمود سن عادي 30% دهون، قطعة ممتازة من أفضل أنواع اللحوم",
  },
  {
    id: 88,
    name: "ريش عجالي ملبس 30%",
    price: 429.99,
    category: "الكندوز",
    image: "/products/ريش-عجالي.png",
    description: "ريش عجالي ملبس 30% دهون، قطعة فاخرة طرية ولذيذة",
  },
  {
    id: 89,
    name: "عمود سن أحمر 10%",
    price: 484.99,
    category: "الكندوز",
    image: "/products/لحم-عمود-سن-قليل-الدسم.png",
    description: "عمود سن أحمر 10% دهون، من أندر القطع وأجودها",
  },
  {
    id: 90,
    name: "عمود سن مميز 20%",
    price: 459.99,
    category: "الكندوز",
    image: "/products/لحم-عمود-سن-قليل-الدسم.png",
    description: "عمود سن مميز 20% دهون، توازن مثالي بين النكهة والصحة",
  },
  {
    id: 93,
    name: "ظهر فخدة",
    price: 474.99,
    category: "الكندوز",
    image: "/products/ظهر-الفخدة.jpg",
    description: "ظهر فخدة بلدي، قطعة ممتازة طرية مثالية للشوي والطبخ",
  },
  {
    id: 94,
    name: "انتروكوت / ستيك",
    price: 479.99,
    category: "الكندوز",
    image: "/products/وانتركوقت-ستيك.png",
    description:
      "انتروكوت ستيك من أجود القطع، مثالي للشوي بدرجة الحرارة المفضلة",
  },
  {
    id: 95,
    name: "انتروكوت / قطع",
    price: 479.99,
    category: "الكندوز",
    image: "/products/وانتركوقت-ستيك.png",
    description: "انتروكوت مقطع جاهز للطبخ، جودة استثنائية من بيت اللحوم",
  },
  {
    id: 96,
    name: "موزة",
    price: 479.99,
    category: "الكندوز",
    image: "/products/لحمة-موزة.png",
    description: "لحمة موزة بلدي، قطعة فاخرة طرية من أفضل القطع",
  },
  {
    id: 97,
    name: "بوفتيك",
    price: 489.99,
    category: "الكندوز",
    image: "/products/بوفتيك.png",
    description: "بوفتيك بلدي ممتاز، قطعة نادرة ولذيذة جداً",
  },
  {
    id: 98,
    name: "وش فخدة",
    price: 489.99,
    category: "الكندوز",
    image: "/products/وش-فخدة.png",
    description: "وش فخدة بلدي، من ألذ القطع وأكثرها طلباً",
  },
  {
    id: 99,
    name: "فلتو",
    price: 499.99,
    category: "الكندوز",
    image: "/products/عرق-فلتو.png",
    description: "عرق فلتو بلدي، قطعة استثنائية فاخرة جداً",
  },
  {
    id: 100,
    name: "عرق ترياناكو",
    price: 484.99,
    category: "الكندوز",
    image: "/products/dummy.png",
    description: "عرق ترياناكو فاخر، قطعة مميزة بطعم لا مثيل له",
  },
  {
    id: 101,
    name: "كتف عجالي",
    price: 479.99,
    category: "الكندوز",
    image: "/products/dummy.png",
    description: "كتف عجالي بلدي ممتاز، مثالي للطبخ البطيء والشوي",
  },
  {
    id: 102,
    name: "سمانه",
    price: 489.99,
    category: "الكندوز",
    image: "/products/سمانة.png",
    description: "سمانه بلدي، قطعة فاخرة طرية من أجود الذبائح",
  },
  {
    id: 103,
    name: "قشرة",
    price: 479.99,
    category: "الكندوز",
    image: "/products/صباع-قشرة-لحمة-باردة.png",
    description: "صباع قشرة لحمة باردة، مقرمشة ولذيذة من أشهى المقبلات",
  },
];

export const categories: Category[] = [
  {
    key: "جاهز للتسوية",
    label: "جاهز للتسوية",
    icon: Flame,
    image: "/images/cat-ready.png",
    gradient: "from-crimson to-crimson-dark",
    badge: "الأكثر طلباً",
    products: allProducts.filter((p) => p.category === "جاهز للتسوية"),
  },
  {
    key: "الكندوز",
    label: "الكندوز",
    icon: Crown,
    image: "/images/cat-premium.png",
    gradient: "from-gold to-gold-dark",
    badge: "مميز",
    products: allProducts.filter((p) => p.category === "الكندوز"),
  },
  {
    key: "حجز مسبق",
    label: "حجز مسبق",
    icon: Sparkles,
    image: "/images/cat-preorder.png",
    gradient: "from-charcoal-lighter to-charcoal-light",
    badge: "حجز الآن",
    products: allProducts.filter((p) => p.category === "حجز مسبق"),
  },
];
